Repository mpx-ecology/mpx-cli, pull requests merged in 2022-10, with the labels that each got.

#49 Bugfix/ts
  packages/vue-cli-plugin-mpx-typescript/generator/template-tsconfig/tsconfig.json
Labels: bug

#50 Feat eslint bugfix
  packages/vue-cli-plugin-mpx-cloud-func/generator/template-typescript/src/miniprogram/app.ts
  packages/vue-cli-plugin-mpx-cloud-func/generator/template-typescript/src/miniprogram/pages/index.ts
  packages/vue-cli-plugin-mpx-cloud-func/generator/template/src/miniprogram/app.mpx
  packages/vue-cli-plugin-mpx-cloud-func/generator/template/src/miniprogram/pages/index.mpx
  packages/vue-cli-plugin-mpx-eslint/generator/index.js
  packages/vue-cli-plugin-mpx-eslint/generator/template/_eslintrc.js
  packages/vue-cli-plugin-mpx-plugin-mode/generator/template-typescript/src/miniprogram/app.mpx
  packages/vue-cli-plugin-mpx-plugin-mode/generator/template-typescript/src/miniprogram/pages/index.mpx
  packages/vue-cli-plugin-mpx-plugin-mode/generator/template/src/miniprogram/app.mpx
  packages/vue-cli-plugin-mpx-plugin-mode/generator/template/src/miniprogram/pages/index.mpx
  packages/vue-cli-plugin-mpx-typescript/generator/template-src/src/pages/index.mpx
  packages/vue-cli-plugin-mpx/generator/src/template/src/app.mpx
  packages/vue-cli-plugin-mpx/generator/src/template/src/pages/index.mpx
Labels: bug, PR: Bug Fix

#51 fix: eslint-config error
  packages/vue-cli-plugin-mpx-eslint/generator/index.js
Labels: PR: Bug Fix
